Ready to pr
42ity/fty-srr-rest pull request #2
Opened 2019-10-15 14:31 UTC by MimiXav

2019-10-30 13:30 UTC, boricj approved these changes
Looks good to me.

2019-10-30 13:30 UTC, boricj commented on project.xml
> +    </use>
Duplicated zproject dependencies.

2019-10-30 14:53 UTC, perrettecl requested changes

2019-10-30 14:53 UTC, perrettecl commented on CMakeLists.txt
Remove CMakeLists.txt from the repo

2019-10-31 09:50 UTC, MimiXav commented
Thanks a lot Clement

2019-10-31 09:50 UTC, merged