Using latest SrrFeaturesListDto to be compliant with srr spec
42ity/fty-srr-rest pull request #4
Opened 2019-11-05 15:50 UTC by MimiXav

Signed-off-by: Xavier Millieret <XavierMillieret@eaton.com>

2019-11-05 16:04 UTC, boricj requested changes
Use `std::getline` for tokenization.

2019-11-05 16:04 UTC, boricj commented on src/fty_srr_helpers.cc
> +    return resultList;
Consider using `std::getline`:
```c++
std::stringstream input("denmark;sweden;india;us");
std::string token;
while (getline(input, token, ';')) {
    ...
}
```

2019-11-05 16:04 UTC, boricj commented on src/rest_srr_GET.ecpp
> +            siFeaturesList.addMember("") <<= siFeature;
_Note for later: find a way to generate that serialization/deserialization code automatically._

2019-11-06 08:28 UTC, perrettecl approved these changes

2019-11-06 08:37 UTC, boricj approved these changes

2019-11-06 09:03 UTC, merged